### ISSUE TITLE
Unhandled Exception: Exception: FormatException: Bad UTF-8 encoding 0x9 (at offset 28)

### ISSUE THREAD

**Issue by hungthai1401** [klaszlo8207/Flutter-FBX-3D-Viewer#1]
I have this error when open the fpx file downloaded from https://free3d.com/3d-model/ac-cobra-269-83668.html

**Comment by klaszlo8207** [comment]
You can try to convert the file to a latest ascii fbx file and try with that. A sample fbx file can seen in the assets directory.

**Comment by hungthai1401** [comment]
@klaszlo8207 could you have a way to convert the file to the latest ascii fbx format?

**Comment by klaszlo8207** [comment]
https://www.google.com/search?q=convert+binary+fbx+to+ascii

Nguyễn Hưng Thái <notifications@github.com> ezt írta (időpont: 2020. jan.
17., P 7:04):

**Comment by klaszlo8207** [comment]
http://download.autodesk.com/us/fbx/2013/FBXconverter/index.html?url=files/GUID-1FA89D88-D69F-4F08-B941-0118D71BB136.htm,topicNumber=d30e884

Autodesk is the best way

Nguyễn Hưng Thái <notifications@github.com> ezt írta (időpont: 2020. jan.
17., P 7:04):
