### ISSUE TITLE
Would be possible to use multiple textures for the same model controlled via tags?

### ISSUE THREAD

**Issue by vpsantos** [klaszlo8207/Flutter-FBX-3D-Viewer#2]
I would like to create a product configurator where the user is able to change the texture of different parts of the model. On Unity3D for example, I create a prefab of the fbx model and I set different tags for the parts I want to control the materials/textures. Could I do something like this using this library?

Thank you.

**Comment by klaszlo8207** [comment]
You can create an extension on this library. So you can basically do everything if you create it. Please feel free to add new features
