### ISSUE TITLE
Example Project not working

### ISSUE THREAD

**Issue by Ahmadre** [klaszlo8207/Flutter-FBX-3D-Viewer#3]
At first: thank you for your work and this package :).

I was trying jus to render your example project but I am getting this error:
<img width="400" alt="Bildschirmfoto 2020-06-02 um 22 48 41" src="https://user-images.githubusercontent.com/18512224/83569104-4bf56300-a524-11ea-80b9-2a96ea72dc50.png">

I don't know what's going on. 

But this is what I am getting out of my console: 
```
 EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building Example(dirty, state: _ExampleState#8721a):
flutter: MediaQuery.of() called with a context that does not contain a MediaQuery.
flutter: No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of().
flutter: This can happen because you do not have a WidgetsApp or MaterialApp widget (those widgets introduce
flutter: a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.
flutter: The context used was:
flutter:   Example
flutter:
flutter: The relevant error-causing widget was:
flutter:   Example file:///Users/rebar/Documents/Flutter_Plugins_Fork/flutter_demo_3d/lib/main.dart:12:10
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      MediaQuery.of (package:flutter/src/widgets/media_query.dart:813:5)
flutter: #1      ScreenUtils.init (package:flutter_fbx3d_viewer/fbx_viewer/utils/screen_utils.dart:11:27)
flutter: #2      _ExampleState.build (package:flutter_demo_3d/main.dart:150:17)
flutter: #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4628:28)
flutter: #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4511:15)
flutter: #5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4684:11)
flutter: #6      Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
flutter: #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2632:33)
flutter: #8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:864:20)
flutter: #9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
flutter: #10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
flutter: #11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
flutter: #12     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:861:7)
flutter: (elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)
flutter:
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by Ahmadre** [comment]
By the way: you got no main function in your example code.

**Comment by Ahmadre** [comment]
When I insert this:

```
void main() {
  runApp(
    MaterialApp(home: Example()),
  );
}
```

I am getting this now:

<img width="411" alt="Bildschirmfoto 2020-06-02 um 23 01 14" src="https://user-images.githubusercontent.com/18512224/83569561-f79eb300-a524-11ea-99d1-83bc829f9ad2.png">

**Comment by Ahmadre** [comment]
I just want to show a single file, why is it so hard to use this?

**Comment by Ahmadre** [comment]
I got it working now with:

```
void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider<ChangeVariants>.value(
      value: ChangeVariants(),
      builder: (context, widget) => MaterialApp(
        home: Example(),
      ),
    );
  }
}
```

but this is shown:
<img width="414" alt="Bildschirmfoto 2020-06-02 um 23 36 22" src="https://user-images.githubusercontent.com/18512224/83572435-df7d6280-a529-11ea-82b9-421f9a4fe805.png">

**Comment by klaszlo8207** [comment]
The error is shown: skinIndices not set in the fbx file

**Comment by Ahmadre** [comment]
@klaszlo8207 sure, this is the chipmunk from the example ^^

**Comment by klaszlo8207** [comment]
> @klaszlo8207 sure, this is the chipmunk from the example ^^

As u can see in the video:

https://youtu.be/hTnkwEGFu9k

This is the good behaviour. I used the chipmunk only for demonstrating the error handling...

**Comment by risangpinto** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
lero003, @ray-learn, @dade80vr, @Saka7, @chevronkey, @brobrojrod, @stevewaffles, @ninacat25, @jerryDrumm, @Techchild7, @Schoss, @dnev1551, @kevinnguyenai, @bcrigler, @adotsloan, @ljluestc, @paradoxicalNL, @jirkaformanek, @hemantasapkota, @kerrtravers, @be1box, @wyrover, @FormusohDinga, @tonyrevo, @thiagoghisicrypto, @leventozen, @cucuso, @o3LL, @nimbosa, @justHungryMan, @Winglonelion, @mydxnh, @Andrey543543, @mortezabahmani, @ellen-du, @YazaiHu, @noshitsecurity, @flmuel, @peterpme, @freshduer, @kidbomb, @mjvignesh, @kflwasjkl, @carsrlife, @diveyez, @godratio, @gummideepak, @IgorKonovalov, @orhanbalci174, @jinyahuanraj-indulkar, @ali-raheem, @supportlivecoin, @firhatnawfanh, @g0dspeak, @cdrrazan, @chrislonge, @quantmod, @pybizzle, @Almolhem, @nicolas-martin, @BeholdAdam, @Max-Meldrum, @deaconudanandrei, @0xdevalias, @fayazg, @ariellephan, @Kurre, @soSeriousSec, @hiroki1117, @fantuz, @mstarnes, @pcondreicsik, @fanhuaqiang, @oleersoy, @blancosj, @drmzio, @xvgPedro, @xMoad, @yamshik1, @ecorvo, @black23, @farbodataie, @sheldon111, @tripstylin, @ornedaj, @astronaut1712, @kael4n, @medenfield, @Jackneill, @EMCarrasco, @kamal-ganwani, @favazmohd, @ktomov, @eshbeata, @alighazi, @thiagoghisi, @Feargalicious, @ozanh, @Carloskorrane

**Comment by Ahmadre** [comment]
> > @klaszlo8207 sure, this is the chipmunk from the example ^^
> 
> As u can see in the video:
> 
> https://youtu.be/hTnkwEGFu9k
> 
> This is the good behaviour. I used the chipmunk only for demonstrating the error handling...

Oh Thanks :) i didn't know that! Awesome package! Thanks :)
