### ISSUE TITLE
Constrain viewer width and height?

### ISSUE THREAD

**Issue by devpascoe** [klaszlo8207/Flutter-FBX-3D-Viewer#5]
I've tried wrapping in a SizedBox etc but the fbx widget always jumps fullscreen. Anyway i can shrink it down into a smaller box or does the viewer always have to be fullscreen?

**Comment by devpascoe** [comment]
More attempts to wrap in Container and SizedBox widgets i am unable to keep the FBX widget from blowing out fullscreen. Any tips?

**Comment by klaszlo8207** [comment]
You can try the

size: Size(ScreenUtils.width, ScreenUtils.height),

On the Fbx3DViewer widget
