### ISSUE TITLE
How to load fbx file of by encode content?

### ISSUE THREAD

**Issue by qiuguian** [klaszlo8207/Flutter-FBX-3D-Viewer#7]
fbx fiel  =>  Kaydara FBX Binary  L�FBXHeaderExtensiontFBXHeaderVersionI��
FBXVersionIL�EncryptionTypeI)CreationTimeStampVersionI�9YearI�\MonthI}DayI�HourI�MinuteI5�SecondI5MillisecondIdr)CreatorS$FBX SDK/FBX Plugins version 2018.1.1�'	SceneInfoSGlobalInfoSceneInfoSUserData�
TypeSUserData
VersionIdFMetaDataPVersionIdsTitleS�SubjectS�AuthorS�KeywordsSRevisionS-CommentS�Properties70�PPSDocumentUrlSKStringSUrlSS"C:\Users\ADMINI~1\Desktop\1111.fbxBSPSSrcDocumentUrlSKStringSUrlSS"C:\Users\ADMINI~1\Desktop\1111.fbx�$PSOriginalSCompoundSS�:PSOriginal|ApplicationVendorSKStringSSS&8PSOriginal|ApplicationNameSKStringSSS{;PSOriginal|ApplicationVersionSKStringSSS�6PSOriginal|DateTime_GMTSDateTimeSSS1PSOriginal|FileNameSKStringSSSU%PS	LastSavedSCompoundSS�;PSLastSaved|ApplicationVendorSKStringSSS�9PSLastSaved|ApplicationNameSKStringSSSS<PSLastSaved|ApplicationVersionSKStringSSS�7PSLastSaved|DateTime_GMTSDateTimeSSS#	FileIdR-�,�#���˰#�'��d	CreationTimeS2020-04-04 14:53:53:100�	8CreatorS3FBX SDK/FBX Plugins version 2018.1.1 build=20170505MGlobalSettings
VersionI�4Properties70p......

**Comment by klaszlo8207** [comment]
FBX Version: FBX 2014/2015 -> Export

SAVE -> .fbx (ASCII)

You can convert the file to this type. The lib cannot handle all the fbx
versions and the binary files.

**Comment by qiuguian** [comment]
@klaszlo8207  Thanks
